name: friends
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.0.5 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  # platform_device_id: ^1.0.1
  cached_network_image: ^3.2.3
  zoom_tap_animation: ^1.1.0
  url_launcher: ^6.1.11

  # package_info_plus: ^4.0.2
  dio: ^5.0.0
  get: 4.6.5
  flutter: 
    sdk: flutter

dev_dependencies: 
  # flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

